#! /bin/sh

export EDITOR=nvim
export QT_QPA_PLATFORMTHEME="qt5ct"  

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

fcitx5 &

xinput --set-prop "ELAN1300:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1 &
#setxkbmap -option grp:alt_shift_toggle us,es &
xsetroot -cursor_name left_ptr &
unclutter &
light -S 50 &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
#wal -R
picom -f -b &
xss-lock -l $HOME/.config/scripts/lock.sh &
xfce4-power-manager &
blueberry-tray &
nm-applet &
gnome-keyring-daemon --start --components=pkcs11 &

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config normal_border_color   '#282c34'
bspc config active_border_color   '#3d4148'
bspc config focused_border_color  '#282c34'
bspc config presel_feedback_color '#abb2bf'

# Pywal config
#bspc config normal_border_color   "$color1"
#bspc config active_border_color   "$color8"
#bspc config focused_border_color  "$color1"
#bspc config presel_feedback_color "$color15"

bspc config border_width          4
bspc config window_gap            15
bspc config top_padding 		      24
bspc config bottom_padding 		    0
bspc config left_padding 		      0
bspc config right_padding 		    0
bspc config honor_size_hints		  true
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus 		false
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a Galculator state=floating
